### ISSUE TITLE
Install Intel Parallel Studio Composer Edition 2017

### ISSUE THREAD

**Issue by mikecroucher** [rcgsheffield/sheffield_hpc#359]
This is the first release of this series. It includes version 17 of the compilers.

I've put the installer in `/fastdata/fe1mpc/public`

**Comment by willfurnass** [comment]
Doesn't contain tarballs; only RPMs and cabs.  Is this what's needed for adding a new version of the Intel compilers on our HPC machines?

**Comment by willfurnass** [comment]
To do:

- [ ] Install script (see #413 for how done on ShARC)
- [ ] Module files for each of: compilers, TBB, IPP, MKL and DAAL  (see #413 for how done on ShARC)
- [ ] License config for compilers
- [ ] Testing
- [ ] Documentation for 5 components and PS as a whole  (see #413 for how done on ShARC)

NB Latest TBB is a priority as it's to be used for a forthcoming course (#412)

**Comment by willfurnass** [comment]
Hmm, the Intel Parallel Studio Composer Edition installer may not like the OS on Iceberg:

```
$ iceberg/software/install_scripts/compilers/intel-ps-xe-ce/2017.0//install.sh
Missing optional prerequisites
-- Unsupported OS
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
There are some missing optional prerequisites. If you still want to continue,
please correct the CONTINUE_WITH_OPTIONAL_ERROR variable in silent configuration
file.
```

```
$ cat /etc/issue
Scientific Linux release 6.8 (Carbon)
```
